nama    = input("masukkan nama    : ")
umur    = input("masukkan umur    : ")
alamat  = input("masukkan alamat  : ")
jurusan = input("masukkan jurusan : ")

print("\n---biodaata---")
print("nama    : " + nama)
print("umur    : " + umur)
print("alamat  : " + alamat)
print("jurusan : " + jurusan)
